export const DistrictsArray = [
    "Fatehabad",
    "Sirsa",
    "Hisar",
    "Bhiwani",
    "Rohtak",
    "Jhajjar",
    "Mahendragarh",
    "Rewari",
    "Gurgaon",
    "Faridabad",
    "Chamba",
    "Kangra",
    "Lahul & Spiti",
    "Kullu",
    "Mandi",
    "Una",
    "Solan",
    "Sirmaur",
    "Shimla",
    "Kinnaur",
    "Bilaspur (HP)",
    "Hamirpur(HP)",
    "Kupwara",
    "Budgam",
    "Poonch",
    "Rajauri",
    "Kathua",
    "Baramulla",
    "Srinagar",
    "Ganderbal",
    "Pulwama",
    "Ananthnag",
    "Kulgam",
    "Doda",
    "Udhampur",
    "Jammu",
    "Kasargod",
    "Kannur",
    "Wayanad",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Thrissur",
    "Ernakulam",
    "Idukki",
    "Kottayam",
    "Alappuzha",
    "Pathanamthitta",
    "Kollam",
    "Thiruvananthapuram",
    "Nandurbar",
    "Dhule",
    "Jalgaon",
    "Buldhana",
    "Akola",
    "Washim",
    "Amravati",
    "Wardha",
    "Nagpur",
    "Bhandara",
    "Gondia",
    "Gadchiroli",
    "Chandrapur",
    "Yavatmal",
    "Nanded",
    "Hingoli",
    "Parbhani",
    "Jalna",
    "Aurangabad",
    "Nashik",
    "Thane",
    "Mumbai",
    "Pune",
    "Ahmed Nagar",
    "Beed",
    "Latur",
    "Osmanabad",
    "Solapur",
    "Satara",
    "Ratnagiri",
    "Sindhudurg",
    "Kolhapur",
    "Sangli",
    "Raigarh(MH)",
    "Senapati",
    "Tamenglong",
    "Churachandpur",
    "Bishnupur",
    "Thoubal",
    "Imphal West",
    "Imphal East",
    "Ukhrul",
    "Chandel",
    "West Garo Hills",
    "East Garo Hills",
    "South Garo Hills",
    "West Khasi Hills",
    "Ri Bhoi",
    "East Khasi Hills",
    "Jaintia Hills",
    "Belagavi",
    "Bagalkot",
    "Vijayapura",
    "Bidar",
    "Raichur",
    "Koppal",
    "Gadag",
    "Dharwad",
    "Uttara Kannada",
    "Haveri",
    "Ballari",
    "Chitradurga",
    "Davangere",
    "Shivamogga",
    "Udupi",
    "Kachchh",
    "Banaskantha",
    "Patan",
    "Mahesana",
    "Sabarkantha",
    "Gandhi Nagar",
    "Ahmedabad",
    "Surendra Nagar",
    "Rajkot",
    "Jamnagar",
    "Porbandar",
    "Junagadh",
    "Amreli",
    "Bhavnagar",
    "Anand",
    "Kheda",
    "Panch Mahals",
    "Vadodara",
    "Narmada",
    "Bharuch",
    "The Dangs",
    "Navsari",
    "Valsad",
    "Surat",
    "Dahod",
    "Panchkula",
    "Ambala",
    "Yamuna Nagar",
    "Guntur",
    "Prakasam",
    "Nellore",
    "Cuddapah",
    "Kurnool",
    "Ananthapur",
    "Chittoor",
    "Kokrajhar",
    "Dhubri",
    "Goalpara",
    "Barpeta",
    "Marigaon",
    "Nagaon",
    "Sonitpur",
    "Lakhimpur",
    "Dhemaji",
    "Tinsukia",
    "Dibrugarh",
    "Sibsagar",
    "Jorhat",
    "Golaghat",
    "Karbi Anglong",
    "North Cachar Hills",
    "Cachar",
    "East Godavari",
    "West Godavari",
    "Krishna",
    "Karimganj",
    "Hailakandi",
    "Bongaigaon",
    "Kamrup",
    "Nalbari",
    "Darrang",
    "Chandigarh",
    "North West Delhi",
    "North Delhi",
    "East Delhi",
    "Central Delhi",
    "West Delhi",
    "South West Delhi",
    "South Delhi",
    "Kurukshetra",
    "Kaithal",
    "Karnal",
    "Panipat",
    "Sonipat",
    "Jind",
    "Khammam",
    "Jayashankar",
    "Daman",
    "Palamau",
    "Latehar",
    "Hazaribag",
    "Ramgarh",
    "Dumka",
    "Jamtara",
    "Ranchi",
    "Gumla",
    "Simdega",
    "West Singhbhum",
    "Seraikela-kharsawan",
    "Uttarkashi",
    "Chamoli",
    "Rudraprayag",
    "Tehri Garhwal",
    "Dehradun",
    "Pauri Garhwal",
    "Pithoragarh",
    "Bageshwar",
    "Almora",
    "Champawat",
    "Nainital",
    "Udham Singh Nagar",
    "Haridwar",
    "Adilabad",
    "Nizamabad",
    "Karim Nagar",
    "Medak",
    "Hyderabad",
    "K.V.Rangareddy",
    "Mahabub Nagar",
    "Nalgonda",
    "Warangal",
    "Aligarh",
    "Hathras",
    "Mathura",
    "Agra",
    "Firozabad",
    "Mainpuri",
    "Budaun",
    "Bareilly",
    "Pilibhit",
    "Shahjahanpur",
    "Kheri",
    "Sitapur",
    "Hardoi",
    "Unnao",
    "Lucknow",
    "Raebareli",
    "Farrukhabad",
    "Kannauj",
    "Etawah",
    "Auraiya",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Jalaun",
    "Jhansi",
    "Lalitpur",
    "Hamirpur",
    "Mahoba",
    "Banda",
    "Chitrakoot",
    "Fatehpur",
    "Pratapgarh",
    "Balrampur",
    "Gonda",
    "Siddharthnagar",
    "Basti",
    "Sant Kabir Nagar",
    "Maharajganj",
    "Gorakhpur",
    "Kushinagar",
    "Deoria",
    "Azamgarh",
    "Mau",
    "Ballia",
    "Jaunpur",
    "Ghazipur",
    "Chandauli",
    "Varanasi",
    "Mirzapur",
    "Sonbhadra",
    "Etah",
    "Sant Ravidas Nagar",
    "Koriya",
    "Surguja",
    "Jashpur",
    "Raigarh",
    "Korba",
    "Janjgir-champa",
    "Bilaspur(CGH)",
    "Rajnandgaon",
    "Durg",
    "Raipur",
    "Mahasamund",
    "Dhamtari",
    "Kanker",
    "Bastar",
    "Shivpuri",
    "Tikamgarh",
    "Chhatarpur",
    "Panna",
    "Sagar",
    "Damoh",
    "Satna",
    "Rewa",
    "Neemuch",
    "Mandsaur",
    "Ratlam",
    "Ujjain",
    "Shajapur",
    "Dewas",
    "Dhar",
    "Indore",
    "Barwani",
    "Rajgarh",
    "Vidisha",
    "Bhopal",
    "Sehore",
    "Raisen",
    "Betul",
    "Hoshangabad",
    "Katni",
    "Jabalpur",
    "Narsinghpur",
    "Dindori",
    "Mandla",
    "Chhindwara",
    "Seoni",
    "Hooghly",
    "Bankura",
    "Purulia",
    "Howrah",
    "Kolkata",
    "South 24 Parganas",
    "West Midnapore",
    "East Midnapore",
    "Alipurduar",
    "Kalimpong",
    "Paschim Bardhaman",
    "South Dinajpur",
    "West Sikkim",
    "North Sikkim",
    "South Sikkim",
    "Tawang",
    "West Kameng",
    "Papum Pare",
    "West Siang",
    "East Siang",
    "Changlang",
    "Tirap",
    "Lower Subansiri",
    "Kurung Kumey",
    "Lohit",
    "Longding",
    "Aizawl",
    "Champhai",
    "Lunglei",
    "Lawngtlai",
    "Saiha",
    "North Goa",
    "South Goa",
    "West Champaran",
    "East Champaran",
    "Sitamarhi",
    "Madhubani",
    "Supaul",
    "Araria",
    "Kishanganj",
    "Purnia",
    "Katihar",
    "Madhepura",
    "Saharsa",
    "Darbhanga",
    "Muzaffarpur",
    "Gopalganj",
    "Siwan",
    "Saran",
    "Vaishali",
    "Samastipur",
    "Begusarai",
    "Khagaria",
    "Bhagalpur",
    "Banka",
    "Munger",
    "Lakhisarai",
    "Sheikhpura",
    "Nalanda",
    "Patna",
    "Bhojpur",
    "Buxar",
    "Kaimur (Bhabua)",
    "Rohtas",
    "Aurangabad(BH)",
    "Gaya",
    "Nawada",
    "Jamui",
    "Jehanabad",
    "Arwal",
    "Sheopur",
    "Morena",
    "Bhind",
    "Gwalior",
    "Datia",
    "Balaghat",
    "Guna",
    "Ashok Nagar",
    "Shahdol",
    "Anuppur",
    "Sidhi",
    "Jhabua",
    "Alirajpur",
    "East Nimar",
    "Khandwa",
    "Burhanpur",
    "West Nimar",
    "Sainkheda",
    "Saharanpur",
    "Muzaffarnagar",
    "Bijnor",
    "Moradabad",
    "Rampur",
    "Jyotiba Phule Nagar",
    "Meerut",
    "Bagpat",
    "Ghaziabad",
    "Gautam Buddha Nagar",
    "Bulandshahr",
    "Kaushambi",
    "Allahabad",
    "Barabanki",
    "Faizabad",
    "Ambedkar Nagar",
    "Sultanpur",
    "Bahraich",
    "Dantewada",
    "Bijapur(CGH)",
    "Chatra",
    "Koderma",
    "Giridh",
    "Deoghar",
    "Godda",
    "Sahibganj",
    "Pakur",
    "Dhanbad",
    "Bokaro",
    "Lohardaga",
    "East Singhbhum",
    "Mandya",
    "Hassan",
    "Dakshina Kannada",
    "Kodagu",
    "Mysuru",
    "Chamrajnagar",
    "Kalaburagi",
    "Yadgir",
    "Kolar",
    "Bengaluru",
    "Bangalore Rural",
    "Ramanagar",
    "Mon",
    "Mokokchung",
    "Wokha",
    "Dimapur",
    "Phek",
    "Longleng",
    "Kiphire",
    "Kohima",
    "Peren",
    "Bargarh",
    "Jharsuguda",
    "Sambalpur",
    "Debagarh",
    "Sundergarh",
    "Kendujhar",
    "Mayurbhanj",
    "Baleswar",
    "Bhadrak",
    "Kendrapara",
    "Jagatsinghapur",
    "Cuttack",
    "Jajapur",
    "Dhenkanal",
    "Nayagarh",
    "Khorda",
    "Puri",
    "Kalahandi",
    "Rayagada",
    "Koraput",
    "Malkangiri",
    "Angul",
    "Nabarangapur",
    "Sonapur",
    "Pondicherry",
    "Karaikal",
    "Gurdaspur",
    "Kapurthala",
    "Jalandhar",
    "Hoshiarpur",
    "Nawanshahr",
    "Fatehgarh Sahib",
    "Ludhiana",
    "Moga",
    "Firozpur",
    "Muktsar",
    "Faridkot",
    "Bathinda",
    "Mansa",
    "Patiala",
    "Amritsar",
    "Tarn Taran",
    "Rupnagar",
    "Ropar",
    "Mohali",
    "Sangrur",
    "Barnala",
    "Pathankot",
    "Ganganagar",
    "Hanumangarh",
    "Bikaner",
    "Churu",
    "Jhujhunu",
    "Alwar",
    "Bharatpur",
    "Dholpur",
    "Karauli",
    "Jaisalmer",
    "Barmer",
    "Jalor",
    "Sirohi",
    "Pali",
    "Ajmer",
    "Tonk",
    "Bundi",
    "Bhilwara",
    "Rajsamand",
    "Dungarpur",
    "Banswara",
    "Chittorgarh",
    "Kota",
    "Baran",
    "Jhalawar",
    "Udaipur",
    "Tiruvallur",
    "Chennai",
    "Kanchipuram",
    "Vellore",
    "Tiruvannamalai",
    "Villupuram",
    "Cuddalore",
    "Nagapattinam",
    "Tiruvarur",
    "Thanjavur",
    "Pudukkottai",
    "Sivaganga",
    "Madurai",
    "Theni",
    "Virudhunagar",
    "Ramanathapuram",
    "Tuticorin",
    "Tirunelveli",
    "Kanyakumari",
    "Dharmapuri",
    "Krishnagiri",
    "Coimbatore",
    "West Tripura",
    "South Tripura",
    "Dhalai",
    "North Tripura",
    "Gomti",
    "Darjiling",
    "Jalpaiguri",
    "Cooch Behar",
    "North Dinajpur",
    "Malda",
    "Murshidabad",
    "Birbhum",
    "Purba Bardhaman",
    "Burdwan",
    "Nadia",
    "North 24 Parganas",
    "Salem",
    "Namakkal",
    "Erode",
    "Nilgiris",
    "Dindigul",
    "Karur",
    "Tiruchirappalli",
    "Perambalur",
    "Ariyalur",
    "Sawai Madhopur",
    "Dausa",
    "Jaipur",
    "Sikar",
    "Nagaur",
    "Jodhpur",
    "Ganjam",
    "Gajapati",
    "Kandhamal",
    "Boudh",
    "Balangir",
    "Nuapada",
    "Chikkamagaluru",
    "Tumakuru",
    "Nicobar",
    "North And Middle Andaman",
    "Srikakulam",
    "Vizianagaram",
    "Visakhapatnam",
    "South Andaman",
    "Kargil",
    "Reasi",
    "Leh",
    "Dadra & Nagar Haveli",
    "Kakching",
    "Chikkaballapur",
    "Zunhebotto",
    "Tuensang",
    "Keonjhargarh",
    "Mahe",
    "Fazilka",
    "Umaria",
    "Harda",
    "Sheohar",
    "Shrawasti",
    "Garhwa",
    "TIRUPPUR",
    "East Sikkim",
    "Mammit",
    "Serchhip",
    "Rajanna Sircilla",
    "Mahabubabad",
    "Khunti",
    "Upper Subansiri",
    "Lower Dibang Valley",
    "Kolasib",
    "Khargone",
    "Singrauli",
    "Kawardha",
    "Kabirdham",
    "Sepahijala",
    "Siddipet",
    "Khowai",
    "East Kameng",
    "Namsai",
    "Jaribam",
    "Lakshadweep",
    "Suryapet",
    "Narayanpur",
    "Tapi",
    "Bandipur",
    "Diu",
    "Samba",
    "Upper Siang",
    "Dibang Valley",
    "North East Delhi",
    "Hapur",
    "Tengnoupal",
    "Medinipur",
    "New Delhi",
    "Kangpokpi",
    "Shopian",
    "Gariaband",
    "MORBI",
    "Peddapalli",
]