import swaggerAutogen from 'swagger-autogen';

import usersDefinitions from './swaggerDocs/usersDefinitions.js';

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3010",
    basePath: "/",
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Users",
            "description": "",
        },
        {
            "name": "Follow",
            "description": "", 
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
    },
    definitions: {
        LoginData: { Token: "string", RefreshToken: "string", CurrentUser: { Role: "User", UserId: "" } },
        ...usersDefinitions
    }
}





const generateSwaggerDocs = async () => {

    const endpointsFiles = ['./routes/index.js']
    const outputFile = './swaggerOutput.json';

    swaggerAutogen(outputFile, endpointsFiles, doc)
};

generateSwaggerDocs();