name: Create Pull Request

on:
  push:
    branches:
      - Develop-Vedanth # Replace with your source branch name

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        env:
          GH_PAT: ${{ secrets.Haris_Token }}
        run: |
          PR_EXISTS=$(curl -s -H "Authorization: token $GH_PAT" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:Develop-Vedanth&base=DebugServer" | jq '. | length')

          if [ "$PR_EXISTS" -eq 0 ]; then
            curl -X POST -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title":"Auto PR from Develop-Vedanth to DebugServer","head":"Develop-Vedanth","base":"DebugServer","body":"This PR was automatically created by a GitHub Action."}' \
            https://api.github.com/repos/${{ github.repository }}/pulls
          else
            echo "Pull request already exists."
          fi

